[package]
name = "jupiter-io"
version = "0.2.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-runtime-interface = { path = "../../../primitives/runtime-interface", default-features = false }

[dependencies.curve]
package = "megaclite-arkworks"
git = "https://github.com/patractlabs/megaclite.git"
default-features = false
features = ["tests"]
optional = true

[features]
default = ["std"]
std = [
    "curve",
    "sp-runtime-interface/std",
]
