[package]
authors = ['Anonymous']
edition = '2018'
name = 'pallet-template'
version = "2.0.0"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet template for defining custom runtime logic."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
megaclite = { git = "https://github.com/patractlabs/megaclite.git", default-features = false, branch = "features/conditional-compile" }
frame-benchmarking = { version = "2.0.0", path = "../../../../frame/benchmarking", optional = true, default-features = false }

[dependencies.frame-support]
default-features = false
version = "2.0.0"
path = "../../../../frame/support"

[dependencies.frame-system]
default-features = false
version = "2.0.0"
path = "../../../../frame/system"

[dependencies.sp-runtime]
default-features = false
version = "2.0.0"
path = "../../../../primitives/runtime"

[dependencies.sp-std]
default-features = false
version = "2.0.0"
path = "../../../../primitives/std"

[dev-dependencies.sp-core]
default-features = false
version = "2.0.0"
path = "../../../../primitives/core"

[dev-dependencies.sp-io]
default-features = false
version = "2.0.0"
path = "../../../../primitives/io"

[dev-dependencies.sp-runtime]
default-features = false
version = "2.0.0"
path = "../../../../primitives/runtime"


[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
    'frame-benchmarking/std',
    'sp-runtime/std',
]
runtime-benchmarks = [
    "frame-benchmarking",
    'frame-system/runtime-benchmarks',
    'frame-support/runtime-benchmarks',
    'sp-runtime/runtime-benchmarks',
]