name: Build && Tests

on:
  push:
    branches: [ patract-contracts ]
  pull_request:
    branches: [ patract-contracts ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v1
      - name: Set nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-10-05
          target: wasm32-unknown-unknown
          override: true
      - name: Cache substrate deps
        uses: actions/cache@v1
        env:
          cache-name: substrate-cache
        with:
          path: ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./Cargo.lock') }}
      - name: Build && Tests 
        run: |
          git clone https://github.com/patractlabs/jupiter.git --depth=1  ~/jupiter
          cd frame/contracts
          mkdir -p ../../../../primitives
          mv ~/jupiter/primitives/io ../../../../primitives
          cargo build -vv
          cargo test -vv
